name: Build & Release (Win + macOS)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller

      # ⬇️ PyInstaller usa automaticamente hook-ahrs.utils.wmm.py
      - name: Build

        run: pyinstaller --onefile --windowed main.py
        # run: pyinstaller --onefile gait_analysis_gui.py

      - name: Rename binary
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/main.exe DVSS_windows.exe
          else
            mv dist/main DVSS_macos
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: DVSS-${{ runner.os }}
          path: DVSS*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { path: ./release-bin }

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          body: |
            Release automatica generata da push su **main**.
            - Commit: ${{ github.sha }}
            - Piattaforme: Windows & macOS
          artifacts: ./release-bin/**
          token: ${{ secrets.GITHUB_TOKEN }}
